# -*- coding: utf-8 -*-
"""NLP prj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nzUmKSHCP9iy07YQxF0_vXZURZhA7MR

# Step 1: Load and Inspect Your Datasets
"""

import pandas as pd

# Load the datasets (replace with your actual file paths)
try:
    df_sarcasm = pd.read_csv('/content/drive/MyDrive/NLP prj/sarcasm/train-balanced-sarcasm.csv')
    df_jokes = pd.read_csv('/content/drive/MyDrive/NLP prj/humor/shortjokes.csv')
except FileNotFoundError:
    print("Make sure your CSV files are in the correct folders!")
    exit()


# Inspect the sarcasm dataset
print("--- Sarcasm Dataset Info ---")
print(df_sarcasm.head())
print(df_sarcasm.info())
print("\nSarcasm label counts:")
print(df_sarcasm['label'].value_counts())

# Inspect the humor dataset
print("\n--- Humor Dataset Info ---")
print(df_jokes.head())
print(df_jokes.info())



"""## Data preprocessing



"""

df_sarcasm.dropna(subset=['comment'], inplace=True)
df_jokes.dropna(subset=['Joke'], inplace=True)

df_sarcasm_processed = df_sarcasm[['comment', 'label']].copy()
df_jokes_processed = df_jokes[['Joke']].copy()

df_jokes_processed.rename(columns={'Joke': 'comment'}, inplace=True)
df_jokes_processed['label'] = 2

"""## Feature extraction



"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Combine the comment columns
combined_comments = pd.concat([df_sarcasm_processed['comment'], df_jokes_processed['comment']], ignore_index=True)

# Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the combined comments
tfidf_features = tfidf_vectorizer.fit_transform(combined_comments)

# Inspect the shape of the resulting feature matrix
print("Shape of TF-IDF feature matrix:", tfidf_features.shape)

# Optionally inspect the vocabulary (first 100 words)
# print("\nVocabulary (first 100 words):", list(tfidf_vectorizer.vocabulary_.keys())[:100])

"""## Combine and split data


"""

from sklearn.model_selection import train_test_split

# Combine the labels
combined_labels = pd.concat([df_sarcasm_processed['label'], df_jokes_processed['label']], ignore_index=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(tfidf_features, combined_labels, test_size=0.2, random_state=42)

# Verify the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Model selection



"""

# Model Choice Reasoning

# 1. Logistic Regression:
# Advantages: Relatively simple, interpretable, and computationally efficient. Good baseline model for text classification.
# Disadvantages: May not capture complex non-linear relationships in the data as well as more complex models.

# 2. Simple Neural Network (e.g., with a few dense layers):
# Advantages: Can learn more complex patterns in the data than linear models. Can be more powerful than Logistic Regression for larger datasets.
# Disadvantages: Can be more computationally expensive to train. Requires careful tuning of hyperparameters.

# Preliminary Decision:
# Given the large size of the dataset and the potential for complex patterns in sarcasm and humor,
# a simple Neural Network is a good preliminary choice. It offers a balance between complexity and
# computational cost compared to very deep models like LSTMs or Transformers, while likely
# outperforming a simple Logistic Regression on this task. We can start with a basic neural network
# and consider more complex architectures later if needed.

"""## Model training

### Subtask:
Train the selected model (Simple Neural Network) on the training data (`X_train`, `y_train`).

"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model architecture
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(3, activation='softmax')  # 3 classes: 0 (not sarcastic), 1 (sarcastic), 2 (humor)
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train,
                    epochs=1,  # You can adjust the number of epochs
                    batch_size=512, # You can adjust the batch size
                    validation_split=0.2) # Use 20% of training data for validation

# Display model summary
model.summary()

"""## Model evaluation



"""

import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Make predictions on the test set
y_pred_probs = model.predict(X_test)

# Convert predicted probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

"""## Make predictions on new data


"""

new_comments = [
    "This is a truly amazing comment! I love it.", # Example of non-sarcastic/non-humorous
    "Wow, that was hilarious! I can't stop laughing.", # Example of humor
    "Oh, you're *so* funny. I'm dying of laughter here.", # Example of sarcasm
]


new_comments_features = tfidf_vectorizer.transform(new_comments)

# Make predictions using the trained model
new_predictions_probs = model.predict(new_comments_features)

# Convert predicted probabilities to class labels
# 0: not sarcastic, 1: sarcastic, 2: humor
new_predictions = np.argmax(new_predictions_probs, axis=1)

# Display the predictions
print("Predictions for new comments:")
for comment, prediction in zip(new_comments, new_predictions):
    label = "Not Sarcastic/Humorous" if prediction == 0 else ("Sarcastic" if prediction == 1 else "Humor")
    print(f"Comment: '{comment}' -> Predicted Label: {label}")



"""# Task
Create a simple website using Flask where a user can input text, and the website will use the previously trained TensorFlow model and TF-IDF vectorizer to predict the category of the text. The website should display the prediction result to the user.

## Save the trained model

### Subtask:
Save the trained TensorFlow model and the fitted TF-IDF vectorizer to files so they can be loaded later in the web application.

**Reasoning**:
Save the trained TensorFlow model and the fitted TF-IDF vectorizer to files for later use in the web application.
"""

import pickle
import os

# Create a directory to save the model and vectorizer if it doesn't exist
save_dir = 'model_and_vectorizer'
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

# Save the trained TensorFlow model
model_save_path = os.path.join(save_dir, 'sarcasm_humor_model.h5') # Using HDF5 format
model.save(model_save_path)
print(f"TensorFlow model saved to: {model_save_path}")

# Save the fitted TF-IDF vectorizer
vectorizer_save_path = os.path.join(save_dir, 'tfidf_vectorizer.pkl')
with open(vectorizer_save_path, 'wb') as f:
    pickle.dump(tfidf_vectorizer, f)
print(f"TF-IDF vectorizer saved to: {vectorizer_save_path}")

"""## Choose a web framework

## Create the web application structure
"""

import os

# Define the main application file name
app_file = 'app.py'

# Define the templates folder name
templates_folder = 'templates'

# Define the template file names
index_template = os.path.join(templates_folder, 'index.html')
result_template = os.path.join(templates_folder, 'result.html')

# Create the templates folder if it doesn't exist
if not os.path.exists(templates_folder):
    os.makedirs(templates_folder)
    print(f"Created directory: {templates_folder}")

# Create the main application file if it doesn't exist
if not os.path.exists(app_file):
    with open(app_file, 'w') as f:
        f.write("# Flask application goes here\n")
    print(f"Created file: {app_file}")

# Create the index.html template file if it doesn't exist
if not os.path.exists(index_template):
    with open(index_template, 'w') as f:
        f.write("<!-- index.html content goes here -->\n")
    print(f"Created file: {index_template}")

# Create the result.html template file if it doesn't exist
if not os.path.exists(result_template):
    with open(result_template, 'w') as f:
        f.write("<!-- result.html content goes here -->\n")
    print(f"Created file: {result_template}")

print("Basic Flask application structure created.")

"""## Load the model and vectorizer


"""

from flask import Flask
import tensorflow as tf
import pickle
import os

# Define the paths to the saved model and vectorizer
# Assuming 'model_and_vectorizer' is in the same directory as app.py
model_save_path = os.path.join('model_and_vectorizer', 'sarcasm_humor_model.h5')
vectorizer_save_path = os.path.join('model_and_vectorizer', 'tfidf_vectorizer.pkl')

# Load the trained TensorFlow model
try:
    model = tf.keras.models.load_model(model_save_path)
    print(f"TensorFlow model loaded successfully from: {model_save_path}")
except Exception as e:
    print(f"Error loading TensorFlow model: {e}")
    model = None # Set model to None if loading fails

# Load the fitted TF-IDF vectorizer
try:
    with open(vectorizer_save_path, 'rb') as f:
        tfidf_vectorizer = pickle.load(f)
    print(f"TF-IDF vectorizer loaded successfully from: {vectorizer_save_path}")
except Exception as e:
    print(f"Error loading TF-IDF vectorizer: {e}")
    tfidf_vectorizer = None # Set vectorizer to None if loading fails


# Initialize Flask application
app = Flask(__name__)

# Add a simple route to verify the app is running (optional but helpful)
@app.route('/')
def index():
    return "Flask app is running. Model and vectorizer loading status printed in console."

if __name__ == '__main__':
    # This part is typically not needed in a notebook environment
    # but is included for completeness if running app.py directly
    # print("Attempting to run Flask app...")
    # app.run(debug=True)
    pass # Keep this passive in the notebook context

"""## Create a prediction endpoint

"""

from flask import request, render_template

# Define the prediction route
@app.route('/predict', methods=['POST'])
def predict():
    user_input = request.form['text']
    prediction_text = "Error: Model or vectorizer not loaded."

    if model is not None and tfidf_vectorizer is not None:
        try:
            # Preprocess the input text
            input_features = tfidf_vectorizer.transform([user_input])

            # Make a prediction
            prediction_probs = model.predict(input_features)
            predicted_label_index = np.argmax(prediction_probs, axis=1)[0]

            # Map the predicted label index to a human-readable category
            label_map = {0: "Not Sarcastic/Humorous", 1: "Sarcastic", 2: "Humor"}
            prediction_text = label_map.get(predicted_label_index, "Unknown Category")

        except Exception as e:
            prediction_text = f"Error during prediction: {e}"
    else:
        prediction_text = "Error: Model or vectorizer could not be loaded on startup."


    return render_template('result.html', original_text=user_input, prediction=prediction_text)

"""## Design the user interface



"""

# # Create the content for index.html
# index_html_content = """
# <!DOCTYPE html>
# <html>
# <head>
#     <title>Sarcasm and Humor Detector</title>
#     <style>
#         body { font-family: Arial, sans-serif; margin: 20px; }
#         h1 { color: #333; }
#         form { margin-top: 20px; }
#         textarea { width: 80%; height: 100px; padding: 10px; border: 1px solid #ccc; }
#         button { padding: 10px 15px; background-color: #007bff; color: white; border: none; cursor: pointer; }
#         button:hover { background-color: #0056b3; }
#     </style>
# </head>
# <body>
#     <h1>Enter Text to Classify</h1>
#     <form action="/predict" method="post">
#         <textarea name="text" placeholder="Enter your text here..." required></textarea><br>
#         <button type="submit">Predict</button>
#     </form>
# </body>
# </html>
# """

# # Create the content for result.html
# result_html_content = """
# <!DOCTYPE html>
# <html>
# <head>
#     <title>Prediction Result</title>
#     <style>
#         body { font-family: Arial, sans-serif; margin: 20px; }
#         h1 { color: #333; }
#         p { margin-top: 10px; }
#         strong { color: #007bff; }
#     </style>
# </head>
# <body>
#     <h1>Prediction Result</h1>
#     <p><strong>Original Text:</strong> {{ original_text }}</p>
#     <p><strong>Predicted Category:</strong> {{ prediction }}</p>
#     <p><a href="/">Go Back</a></p>
# </body>
# </html>
# """

# # Write the content to the files
# index_template_path = os.path.join('templates', 'index.html')
# result_template_path = os.path.join('templates', 'result.html')

# with open(index_template_path, 'w') as f:
#     f.write(index_html_content)
# print(f"Created/Updated {index_template_path}")

# with open(result_template_path, 'w') as f:
#     f.write(result_html_content)
# print(f"Created/Updated {result_template_path}")

"""## Run the web application


"""

# # Append the standard Flask runner code to app.py
# app_file = 'app.py'

# runner_code = """

# if __name__ == '__main__':
#     # Recommended to run this from a terminal using 'python app.py'
#     # Running directly in some notebook environments might require specific extensions
#     # or can block execution.
#     print("Starting Flask development server...")
#     app.run(debug=True)
# """

# with open(app_file, 'a') as f:
#     f.write(runner_code)

# print(f"Added Flask runner code to {app_file}")

